"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['/Applications/Tkinter-Game-master/THEGAME.py']
DATA_FILES = ['Doom-E1M1_SC-8850.mp3', 'EarthSound.mp3']
OPTIONS = {'iconfile':'MacOS/app.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
